github-batch:
  organization: "javagrunt-com"
  token: "${GH_PAT}"
  redis_host: "${REDIS_HOST}"
  redis_port: "${REDIS_PORT}"
spring:
  application:
    name: "github-batch"
  batch:
    jdbc:
      initialize-schema: "always"
  datasource:
    url: "${DATASOURCE_URL:}"
    username: "${DATASOURCE_USERNAME:}"
    password: "${DATASOURCE_PASSWORD:}"
